## config information

## server config information
server:
  port: 8080
  host: 0.0.0.0
  mode: debug # debug or release
  token_expire_second: 360000
  enable_https: false #后台开启https
  cert_file: #证书文件
  key_file: #私钥文件
  jwt_public_key_path:  #jwt公钥文件
  jwt_private_key_path: #jwt私钥文件
  system_static_file_path: #系统静态文件路径
  banner:
    name: banner.txt
    loading: true

## mysql config information
db:
  host: cmz.cnscl.com.cn
  port: 13316
  username: root
  password: mysql
  database: steven_db
  charset: utf8mb4
  category: mysql
  pool:
    maxIdle: 10
    maxOpen: 50
    maxLifetime: 60
  tablePrefix: t_
  init:
    name: init.sql
    status: false

## redis config information
redis:
  host: 0.0.0.0
  port: 6379
  password: root
  db: 0

